# Generated by Django 2.1.3 on 2018-12-03 10:40

from django.db import migrations, models
import django.db.models.deletion
import util.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('util', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tin', models.CharField(help_text='Tax intra. number', max_length=16, verbose_name='tin')),
                ('label', models.CharField(help_text='The way this object will be represented', max_length=255, verbose_name='Label')),
                ('locale', models.ForeignKey(blank=True, help_text='Locale', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actor_actor_set', to='util.Locale', verbose_name='locale')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_actor.actor_set+', to='contenttypes.ContentType')),
                ('status', util.fields.StatusField(limit_choices_to={'model': 'actor.actor'}, on_delete=django.db.models.deletion.PROTECT, related_name='status_actor_actor_set', to='util.Status', verbose_name='status')),
                ('timezone', models.ForeignKey(help_text='Timezone', on_delete=django.db.models.deletion.PROTECT, related_name='actor_actor_set', to='util.TimeZone', verbose_name='timezone')),
            ],
            options={
                'verbose_name': 'actor',
                'verbose_name_plural': 'actors',
                'ordering': ('label',),
            },
        ),
    ]
