# Generated by Django 2.1.3 on 2018-12-03 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='The way this object will be represented', max_length=255, verbose_name='Label')),
                ('alpha2', models.CharField(help_text='Two letters code', max_length=2, unique=True, verbose_name='alpha2')),
                ('alpha3', models.CharField(help_text='Three letters code', max_length=3, unique=True, verbose_name='alpha3')),
                ('number', models.PositiveSmallIntegerField(help_text='Three digits number code', unique=True, verbose_name='number')),
                ('name_fr', models.CharField(help_text='French common name of the country', max_length=255, unique=True, verbose_name='french name')),
                ('name_en', models.CharField(help_text='English common name of the country', max_length=255, unique=True, verbose_name='english name')),
                ('usage', models.CharField(help_text='Usage name (localised)', max_length=255, unique=True, verbose_name='usage name')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='The way this object will be represented', max_length=255, verbose_name='Label')),
                ('plural', models.CharField(help_text='Plural', max_length=31, verbose_name='plural')),
                ('symbol', models.CharField(help_text='Symbol', max_length=7, verbose_name='symbol')),
                ('iso_code', models.CharField(help_text='Iso 4217 code', max_length=3, verbose_name='iso code')),
                ('value', models.FloatField(blank=True, help_text='amount to 1 euros', null=True, verbose_name='value')),
            ],
            options={
                'verbose_name': 'currency',
                'verbose_name_plural': 'currencies',
            },
        ),
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='The way this object will be represented', max_length=255, verbose_name='Label')),
            ],
            options={
                'verbose_name': 'locale',
                'verbose_name_plural': 'locales',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='The way this object will be represented', max_length=255, verbose_name='Label')),
                ('code', models.CharField(help_text='Two letters code', max_length=5, unique=True, verbose_name='code')),
            ],
            options={
                'verbose_name': 'state',
                'verbose_name_plural': 'states',
            },
        ),
        migrations.CreateModel(
            name='StateCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='The way this object will be represented', max_length=255, verbose_name='Label')),
                ('plural', models.CharField(help_text='Plural label', max_length=127, verbose_name='plural')),
            ],
            options={
                'verbose_name': 'state category',
                'verbose_name_plural': 'state categories',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='The way this object will be represented', max_length=255, verbose_name='Label')),
                ('model', models.CharField(help_text='Model related to the status', max_length=64, verbose_name='model')),
                ('is_default', models.BooleanField(default=False, help_text='Is the status is the default one for the model ?', verbose_name='Is default ?')),
            ],
            options={
                'verbose_name': 'status',
                'verbose_name_plural': 'statuses',
            },
        ),
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='The way this object will be represented', max_length=255, verbose_name='Label')),
            ],
            options={
                'verbose_name': 'timezone',
                'verbose_name_plural': 'timezones',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='The way this object will be represented', max_length=255, verbose_name='Label')),
                ('plural', models.CharField(help_text='Plural', max_length=31, verbose_name='plural')),
                ('symbol', models.CharField(help_text='Symbol', max_length=7, verbose_name='symbol')),
                ('value', models.FloatField(help_text='Value converted in SI Unit', verbose_name='value')),
            ],
            options={
                'verbose_name': 'unit',
                'verbose_name_plural': 'units',
            },
        ),
        migrations.CreateModel(
            name='UnitCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='The way this object will be represented', max_length=255, verbose_name='Label')),
            ],
            options={
                'verbose_name': 'unit category',
                'verbose_name_plural': 'unit categories',
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='category',
            field=models.ForeignKey(help_text='Category', on_delete=django.db.models.deletion.PROTECT, related_name='unit_set', to='util.UnitCategory', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='state',
            name='category',
            field=models.ForeignKey(help_text='State, Province or District', on_delete=django.db.models.deletion.PROTECT, related_name='registry_state_set', to='util.StateCategory', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='state',
            name='country',
            field=models.ForeignKey(help_text='Related country', on_delete=django.db.models.deletion.CASCADE, related_name='state_set', to='util.Country', verbose_name='country'),
        ),
    ]
